sources:
    - ../../CoinTickerPal/Sources
templates:
    - AutoMockable.stencil
output: ../Generated/AutoMockable.swift
args:
    autoMockableTestableImports: ["CoinTickerPal"]
    autoMockableImports: []
